# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('Chronology', '0001_initial'), ('Chronology', '0002_auto_20170128_1524'), ('Chronology', '0003_event_reported'), ('Chronology', '0004_auto_20170129_0103'), ('Chronology', '0005_auto_20170129_1114'), ('Chronology', '0006_frontpagemessage'), ('Chronology', '0007_auto_20170129_1144'), ('Chronology', '0008_auto_20170129_1145'), ('Chronology', '0009_auto_20170129_2023'), ('Chronology', '0010_auto_20170129_2109')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('functions', models.ManyToManyField(blank=True, to='Chronology.Function')),
                ('wiki_pagename', models.CharField(blank=True, default='', max_length=200)),
                ('wiki_summary', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='function_at_the_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chronology.Function'),
        ),
        migrations.AddField(
            model_name='event',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chronology.Person'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='online',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, unique=True)),
                ('banned', models.BooleanField(default=False)),
                ('banned_since', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('neutral', 'Neutral')], max_length=7)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chronology.Event')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chronology.IPAddress')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Chronology.IPAddress'),
        ),
        migrations.CreateModel(
            name='FrontpageMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
