# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chronology', '0001_squashed_0010_auto_20170129_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
